server:  port: 9999spring:  application:    name: ADMIN-SERVER  security:      user:       name: admin       password: satish

eureka:         #tells about the Eureka server details and its refresh time   client:    serviceUrl:      defaultZone: http://localhost:8761/eureka/
      

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS