# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3'

#Define services
services:

  #PostgreSQL Database for the application
  easytobuy-mysql:
    image: "mysql"
    container_name: easytobuy-mysql
    #Volume mounted for database for the storage
    volumes:
      - easytobuy-data:/var/lib/mysql/data
    ports:
      - 3306:3306 # Forward the exposed port 3306 on the container to port 5432 on the host machine

    #Environment variable for DB name, user and password
    environment:
      - MYSQL_DB=microservices
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  #Back-end Spring Boot Application
  easytobuy-app:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
    build: ./EasyToBuy-Product-API
    container_name: easytobuy-app

    #Environment variables for Spring Boot Application.
    environment:
      - DB_SERVER=easytobuy-mysql
      - MYSQL_DB=microservices
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

    ports:
      - 8085:8085 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    links:
      - easytobuy-mysql

  #Fron-end Angular Application
  easytobuy-ui:
    build: ./FRONTEND
    container_name: easytobuy-ui
    ports:
      - 4200:80
    links:
      - easytobuy-app

#Volumes for DB data
volumes:
  easytobuy-data:
