version: '3.7'
services:
  easytobuy-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: microservices
    volumes:
      - easytobuy-volume:/var/lib/mysql
    networks: 
      - easytobuy-network
  
  easytobuy-app:
    build: ./
       
    ports:
      - "8086:8086"
    restart: always
    depends_on: # Start the depends_on first
      - easytobuy-mysql 
    environment:
      RDS_HOSTNAME: easytobuy-mysql
      RDS_PORT: 3306
      RDS_DB_NAME: microservices
      RDS_USERNAME: root
      RDS_PASSWORD: root
    networks:
      - easytobuy-network
# Volumes
volumes:
  easytobuy-volume:

networks:
  easytobuy-network: