apiVersion: v1
kind: Service
metadata:
    name: easytobuy-app
    labels:
        app: easytobuy-app
spec:
    type: NodePort
    ports:
        - port: 8082
          targetPort: 8082
          nodePort: 30012
    selector:
        app: easytobuy-app
