apiVersion: v1
kind: ConfigMap
metadata:
    name: mysql-initdb-config-service
data:
    initdb.sql:
        use microservices;
        CREATE TABLE `user` (
        `id` int NOT NULL,
        `password` varchar(255) DEFAULT NULL,
        `user_name` varchar(255) DEFAULT NULL,
        PRIMARY KEY (`id`)
        );