apiVersion: v1
kind: Service
metadata:
    name: mysql-container
    labels:
        app: mysql-container
spec:
    type: NodePort
    ports:
        - port: 3306
          targetPort: 3306
          nodePort: 30000
    selector:
        app: mysql-container