server:
  port: 8082
spring:
  application:
    name: PRODUCT_SERVICE
  zipkin:    base-url: http://localhost:9411/
  sleuth:    sampler:      probability: 1
 

  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/microservices
    username: root
  jpa:
    hibernate:
      ddl-auto: update
eureka:
 client:
   serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
            
       
    
    
      

    

        