server:
  port: 8081
spring:
  application:
    name: CATEGORY_SERVICE
  datasource:
     password: root
     url: jdbc:mysql://localhost:3306/microservices
     username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update
       
    

     
