server:
  port: 8082
spring:
  application:
    name: CATEGORY_SERVICE
  datasource:
     password: ${RDS_PASSWORD:root}
     url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:microservices}
     username: ${RDS_USERNAME:root}
     platform: mysql
     driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
       ddl-auto: update
       
       
    

     
