server:
  port: 8083
spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  application:
    name: COUPON_SERVICE
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/microservices
    username: root
  jpa:
    hibernate:
      ddl-auto: update
eureka:         #tells about the Eureka server details and its refresh time
 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

